### ISSUE TITLE
Helix instructions seem to be incomplete

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tree-sitter-tact#1]
After following the Helix instructions, I also needed to issue the following two commands:

```shell
$ hx --grammar fetch
$ hx --grammar build
```

otherwise, I didn't get syntax highlighting.

This is my Helix version:
```shell
$ hx --version
helix 23.10 (f6021dd0)
```

**Comment by novusnota** [comment]
Oh, thank you for your keen eye! I used those commands so much for updating various grammars, that I totally forgot to mention them :)

UPD: Added those in!

**Comment by anton-trunov** [comment]
Thanks for the prompt fix!
