### ISSUE TITLE
Tact now allows underscores as numeric separators

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tree-sitter-tact#4]
Please see the issue https://github.com/tact-lang/tact/issues/103. This is now released yet, but will be soon. The relevant part of the updated Tact grammar is [here](https://github.com/tact-lang/tact/blob/23452a897110c349a01faa4a5b3540d969868cc6/src/grammar/grammar.ohm#L187-L195).

**Comment by novusnota** [comment]
Got it. I'll update this, `tact.vim` and prism.js highlighting I did later today. Thanks!

**Comment by anton-trunov** [comment]
Awesome, thanks! Is it this [prism.js PR](https://github.com/PrismJS/prism/pull/3717) you mentioned?

**Comment by novusnota** [comment]
Yes it is. Besides, I've updated those:
1. [ton-docs](https://github.com/ton-community/ton-docs/pull/478) (to mirror Prism.js updates)
2. [tact.vim](https://github.com/tact-lang/tact.vim/issues) (closed all the issues, each with a relevant commit)

This repo (`tree-sitter-tact`) will get an update tomorrow, as adding ternary operator requires a little bit of fine-tuning of the grammar and smaller updates in relevant editor queries :)

**Comment by anton-trunov** [comment]
Thanks for all the updates! 👍
