### ISSUE TITLE
Add tree-sitter-tact to the list of grammars at https://tree-sitter.github.io/tree-sitter

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tree-sitter-tact#7]
There is a list of [language bindings](https://tree-sitter.github.io/tree-sitter/#language-bindings) and a list of [parsers](https://tree-sitter.github.io/tree-sitter/#parsers) at https://tree-sitter.github.io/tree-sitter. I think we should try to add `tree-sitter-tact` there for better discoverability

**Comment by novusnota** [comment]
Great suggestion, made a PR: https://github.com/tree-sitter/tree-sitter/pull/3030
